from fpdf import FPDF
import os
from datetime import datetime

class MedicalReportPDF(FPDF):
    def header(self):
        # Logo (Tata Blue)
        self.set_font('Arial', 'B', 15)
        self.set_text_color(0, 80, 180) 
        self.cell(0, 10, 'NeuroSync Enterprise - Clinical Report', 0, 1, 'C')
        self.ln(5)
        
        # Horizontal Line
        self.set_draw_color(0, 80, 180)
        self.set_line_width(1)
        self.line(10, 25, 200, 25)
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} | Generated by NeuroSync AI (v5.0)', 0, 0, 'C')

    def chapter_title(self, label):
        # Section Header (Blue background)
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(230, 240, 255) # Light Blue
        self.set_text_color(0, 0, 0)
        self.cell(0, 8, f'  {label}', 0, 1, 'L', 1)
        self.ln(2)

    def body_text(self, text):
        # Standard Text
        self.set_font('Arial', '', 10)
        self.multi_cell(0, 5, text)
        self.ln(2)

    def bullet_point(self, text):
        # Indented Bullet
        self.set_font('Arial', '', 10)
        self.cell(5) # Indent
        self.multi_cell(0, 5, f"{chr(149)} {text}") # chr(149) is a bullet dot
        self.ln(1)

def generate_pdf(patient_id, summary_text, stats, filename="report.pdf"):
    pdf = MedicalReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # 1. Patient Metadata Box
    pdf.set_font('Arial', 'B', 11)
    pdf.set_fill_color(245, 245, 245)
    pdf.cell(0, 8, f"Patient ID: {patient_id}   |   Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1, 'L', 1)
    pdf.ln(5)

    # 2. Session Statistics (The "Hard Data")
    pdf.chapter_title("Session Telemetry")
    pdf.set_font('Courier', '', 10)
    pdf.cell(0, 5, f"Total Events Detected:  {stats['total_events']}", 0, 1)
    pdf.cell(0, 5, f"Average Heart Rate:     {int(stats['avg_hr'])} BPM", 0, 1)
    pdf.cell(0, 5, f"Dominant Behavior:      {stats['dominant_symptom']}", 0, 1)
    pdf.ln(5)

    # 3. AI Clinical Analysis (Smart Parsing)
    # We iterate through the AI's lines to format them nicely
    pdf.chapter_title("AI Clinical Analysis (Phi-3)")
    
    lines = summary_text.split('\n')
    for line in lines:
        clean_line = line.strip().replace('**', '') # Remove markdown bolding
        
        if not clean_line:
            continue
            
        if clean_line.startswith('###'):
            # It's a header -> Make it a sub-section
            pdf.ln(3)
            pdf.set_font('Arial', 'B', 11)
            pdf.set_text_color(0, 80, 180)
            pdf.cell(0, 6, clean_line.replace('###', '').strip(), 0, 1)
            pdf.set_text_color(0, 0, 0)
        
        elif clean_line.startswith('*') or clean_line.startswith('-'):
            # It's a bullet point
            pdf.bullet_point(clean_line[1:].strip())
            
        else:
            # Regular text
            pdf.body_text(clean_line)

    # 4. Footer Disclaimer
    pdf.ln(10)
    pdf.set_font('Arial', 'I', 8)
    pdf.set_text_color(150, 0, 0) # Red warning
    pdf.multi_cell(0, 4, "DISCLAIMER: This report is generated by an AI Decision Support System. It is intended for clinical assistance only and does not constitute a final medical diagnosis. Please review video timestamps for verification.")

    # Save
    try:
        pdf.output(filename)
        return filename
    except Exception as e:
        print(f"PDF Error: {e}")
        return filename